### ISSUE TITLE
Empty custom/{files,scripts} directories complains about no files found

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/edge-image-builder#253] opened 2024-02-29 17:12 UTC
```
2024-02-29T17:08:24.021Z	WARN	kubernetes/cluster.go:103	Kubernetes config file '/builds/edge-engineering/stack-validation/eib-temp/kubernetes/config/server.yaml' was not provided
2024-02-29T17:08:24.124Z	FATAL	build/build.go:90	An error occurred building the image: configuring combustion: configuring component "custom files": no files found in directory /builds/edge-engineering/stack-validation/eib-temp/custom/files
github.com/suse-edge/edge-image-builder/pkg/cli/build.Run
	/src/pkg/cli/build/build.go:90
github.com/urfave/cli/v2.(*Command).Run
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279
github.com/urfave/cli/v2.(*Command).Run
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272
github.com/urfave/cli/v2.(*App).RunContext
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337
github.com/urfave/cli/v2.(*App).Run
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main
	/src/cmd/eib/main.go:18
runtime.main
	/usr/lib64/go/1.21/src/runtime/proc.go:267
```

the custom/{files,scripts} folders are empty, I guess this is related to https://github.com/suse-edge/edge-image-builder/issues/242

**Comment by atanasdinov** [comment] 2024-03-01 07:41
No, this is a duplicate of https://github.com/suse-edge/edge-image-builder/issues/176.

**Comment by jdob** [comment] 2024-03-07 14:04
Closing as a duplicate of #176.

**Closed by jdob** 2024-03-07 14:04 UTC
Labels: duplicate, triaged
