### ISSUE TITLE
Resolver breaks when specifing higher level versions for the RPM resolver.

### ISSUE THREAD

**Issue by mpas** [suse-edge/edge-image-builder#271] opened 2024-03-06 15:49 UTC
I am looking for a way to specify higher lever versions for the RPM resolver. 

Trying a package lists like below, `breaks the resolver`.  Or the open-driver cannot be found, or messages that there are conflicts.

```
# trying to resolve all dependencies that work with the specified driver version
packages:
    noGPGCheck: true
    packageList:

      - nvidia-open-driver-G06-signed-kmp-default=545.29.06
      - nvidia-compute-utils-G06
      - nvidia-gl-G06
      - nvidia-container-toolkit
    additionalRepos:
      - url: https://download.nvidia.com/suse/sle15sp5/
      - url: https://nvidia.github.io/libnvidia-container/stable/rpm/x86_64
```

```
# trying to resolve all dependencies that work with compute utils
packages:
    noGPGCheck: true
    packageList:

      - nvidia-open-driver-G06-signed-kmp-default
      - nvidia-compute-utils-G06=545.29.06
      - nvidia-gl-G06
      - nvidia-container-toolkit
    additionalRepos:
      - url: https://download.nvidia.com/suse/sle15sp5/
      - url: https://nvidia.github.io/libnvidia-container/stable/rpm/x86_64
```

```
# trying to specify higher level versions for all dependencies
packages:
    noGPGCheck: true
    packageList:

      - nvidia-open-driver-G06-signed-kmp-default=545.29.06
      - nvidia-compute-utils-G06=545.29.06
      - nvidia-gl-G06=545.29.06
      - nvidia-container-toolkit
    additionalRepos:
      - url: https://download.nvidia.com/suse/sle15sp5/
      - url: https://nvidia.github.io/libnvidia-container/stable/rpm/x86_64
```

Example output of the logs:

In the case below I fixed the version of compute utils but it still want to installs the latest driver that is not compatible.

```
Resolving package dependencies...

Problem: nothing provides 'kernel-azure' needed by the to be installed nvidia-driver-G06-kmp-azure-545.29.06_k5.14.21_150500.31-150500.19.1.x86_64
 Solution 1: Following actions will be done:
  do not install nvidia-gl-G06-545.29.06-150500.19.1.x86_64
  do not install nvidia-compute-utils-G06-545.29.06-150500.19.1.x86_64
 Solution 2: do not install nvidia-open-driver-G06-signed-kmp-default-550.54.14_k5.14.21_150500.55.49-150500.3.36.1.x86_64
 Solution 3: break nvidia-driver-G06-kmp-azure-545.29.06_k5.14.21_150500.31-150500.19.1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/3/c/d/?] (c): c
```

I tried the corresponding installs using Leap Micro (zypper) and there it seems to work well. So wondering what I am missing or doing wrong :)?

**Comment by ipetrov117** [comment] 2024-03-06 15:57
@mpas thanks for raising this. Can you please provide the full log of the `podman-image-build.log`, I am curious whether there are additional errors related to the `https://nvidia.github.io/libnvidia-container/stable/rpm/x86_64` additional repository.

**Comment by rdoxenham** [comment] 2024-03-07 16:11
@mpas OK, I spent a bit of time on this and I think I can see what's going on here...

If I don't specify any versions at all, the resolver logic can figure things out well. Reason being, when we specify `nvidia-compute-utils-G06` it will find this in the `https://download.nvidia.com/suse/sle15sp5/` repo, and there's a corresponding version that matches the `nvidia-open-driver-G06-signed-kmp-default` package in the SLE Micro repos. Hence this works.

The problem is when you specify versions that do not exist in the equivalent NVIDIA repo. If I look in that repo today, it seems that there's only the `550.54.14` version of that package, and the resolver logic will try and force a resolution where it thinks that the only way to satisfy this requirement is to pull in the unsigned kernel module from NVIDIA which is for `kernel-azure`; not what we want.

**Comment by rdoxenham** [comment] 2024-04-02 10:29
Closing this issue given that this isn't a core problem with the way that Edge Image Builder is handling RPM dependency management. This is due to the nature of the changing repo's on the NVIDIA side that we're tracking elsewhere.

**Closed by rdoxenham** 2024-04-02 10:29 UTC
Labels: question, triaged
