### ISSUE TITLE
Building custom image fails on libguestfs error

### ISSUE THREAD

**Issue by mpas** [suse-edge/edge-image-builder#148] opened 2024-02-02 04:23 UTC
I am running the builder with the minimal example on a Mac M1 and get an `libguestfs` error. Not sure what is causing this.

I am building the image using the following configuration:

- Mac M1 Pro (Ventura)
- Colima v0.6.7 (colima start --arch aarch64 --vm-type=vz --vz-rosetta)

Please let me know if any other info is needed!

```yaml
# image definition file
apiVersion: 1.0
image:
  imageType: iso
  arch: x86_64
  baseImage: SLE-Micro.x86_64-5.5.0-Default-SelfInstall-GM.install.iso
  outputImageName: eib-image.iso
```

```shell
# Executed command after successfully building the edge builder docker image
docker run --rm -it \
  -v $IMAGE_DIR:/eib eib:dev /bin/eib \
  -config-file $CONFIG_FILE \
  -config-dir /eib \
  -build-dir /eib/_build
```

```shell
# console output
Building ISO Image with parameters:
IMAGE_DIR = /Users/mpas/Development/scratchpad/eib-test
CONFIG_FILE = eib-config-iso.yaml
BUILD_DIR = /Users/mpas/Development/scratchpad/eib-test/_build
Generating image customization components...
Identifier ................... [SUCCESS]
Custom Files ................. [SKIPPED]
Time ......................... [SKIPPED]
Network ...................... [SKIPPED]
Users ........................ [SKIPPED]
Proxy ........................ [SKIPPED]
Rpm .......................... [SKIPPED]
Systemd ...................... [SKIPPED]
Elemental .................... [SKIPPED]
Suma ......................... [SKIPPED]
Embedded Artifact Registry ... [SKIPPED]
Keymap ....................... [SUCCESS]
Kubernetes ................... [SKIPPED]
Certificates ................. [SKIPPED]
Building ISO image...
Kernel Params ................ [SKIPPED]
Error building ISO image, check the logs under the build directory for more information.
```

```txt
# raw-build.log
libguestfs: error: appliance closed the connection unexpectedly.
This usually means the libguestfs appliance crashed.
Do:
  export LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1
and run the command again.  For further information, read:
  http://libguestfs.org/guestfs-faq.1.html#debugging-libguestfs
You can also run 'libguestfs-test-tool' and post the *complete* output
into a bug report or message to the libguestfs mailing list.
libguestfs: error: /usr/bin/qemu-system-aarch64 exited with error status 1.
To see full error messages you may need to enable debugging.
Do:
  export LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1
and run the command again.  For further information, read:
  http://libguestfs.org/guestfs-faq.1.html#debugging-libguestfs
You can also run 'libguestfs-test-tool' and post the *complete* output
into a bug report or message to the libguestfs mailing list.
libguestfs: error: guestfs_launch failed.
This usually means the libguestfs appliance failed to start or crashed.
Do:
  export LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1
and run the command again.  For further information, read:
  http://libguestfs.org/guestfs-faq.1.html#debugging-libguestfs
You can also run 'libguestfs-test-tool' and post the *complete* output
into a bug report or message to the libguestfs mailing list.
```

**Comment by e-minguez** [comment] 2024-02-02 06:46
I think it maybe related to the fact eib is not supported on arm64 (yet), see https://github.com/suse-edge/edge-image-builder/issues/68

Just in case, can you run the same command with debug enabled?

Note: maybe we need to check the architecture and fail gracefully instead of letting libvirt fail 😅 /cc @jdob

**Comment by mpas** [comment] 2024-02-02 07:23
Will run with debug enabled.. 

What I actually want to achieve is to run eib on my Arm machine and create a x64 ISO image. That is something we have been doing with previous SLE Micro versions /  setups that worked nicely.

So if there are any tips on how to achieve that, then that would be great!

**Comment by mpas** [comment] 2024-02-05 14:45
Have run with debug enabled like in the linked issue.

```
2024-02-05T14:19:05.346Z	INFO	combustion/network.go:50	Configuring network component...
2024-02-05T14:19:05.346Z	INFO	combustion/network.go:54	Skipping network component, configuration is not provided
2024-02-05T14:19:05.346Z	INFO	combustion/rpm.go:32	Skipping RPM component. Configuration is not provided
2024-02-05T14:19:05.346Z	INFO	combustion/elemental.go:29	Skipping elemental registration component, configuration is not provided
2024-02-05T14:19:05.347Z	INFO	combustion/certificates.go:28	skipping certificate configuration, no certificates provided
2024-02-05T14:19:24.390Z	FATAL	eib/main.go:96	An error occurred building the image: modifying the raw image inside of the ISO: running the image modification script: exit status 1
main.main
	/src/cmd/eib/main.go:96
runtime.main
	/usr/lib64/go/1.21/src/runtime/proc.go:267

```

**Comment by mpas** [comment] 2024-02-06 08:24
Related to the message that `Could not access KVM kernel module: No such file or directory`. I tried setting the option `LIBGUESTFS_BACKEND_SETTINGS=force_tcg` inside the `modify-raw-image.sh.tpl`. But this gives another error..

I found this option reading the thread below.
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1740696.html

**Comment by atanasdinov** [comment] 2024-02-08 10:42
Thanks for the interest in this. Unfortunately, the initial release will not support aarch64 but we're definitely looking into introducing it at a later point.

**Comment by jdob** [comment] 2024-02-16 15:32
Closing as a duplicate of the feature request for aarch #193

**Closed by jdob** 2024-02-16 15:32 UTC
